#!/bin/bash

if [ $# != 1 ]
then
    echo "udb <path>"
    exit -1
fi

PWD=$(pwd)

source ~/.bashrc.prj $1

cd $PRJTOP

echo "PRJTOP=" $PRJTOP
echo "SRCLIST=" $SRCLIST
echo "EXCLUDE LIST=" $EXCLIST
mkdir -p $TAGTOP

#prepare filelist for ctags and cscope
for exc in $EXCLIST
do
	EXCLIST_CSCOPE+="-name $exc -prune -o "
done

echo > $TAGTOP/cscope.files
for src in $SRCLIST
do
	find $PRJTOP/$src \( $EXCLIST_CSCOPE -name "*.c" -o -name "*.h" -o -name "*.cpp" -o -name "*.hpp"  -o -name "*.cc"  -o -name "*.mk" -o -name "*akefile" -o -name "*.java" \) -type f>> $TAGTOP/cscope.files
done

#update cscope db
cd $TAGTOP
cscope -Rbqk -i $TAGTOP/cscope.files  2>/dev/null >$TAGTOP/log

#update ctags db
ctags -R -L $TAGTOP/cscope.files  -f $TAGTOP/tags 2>/dev/null >> $TAGTOP/log


#update locate db
echo "v" | sudo -S updatedb --prunepaths $PRJTOP/.repo -U $PRJTOP -o $TAGTOP/.dirlocate.db 2>/dev/null >> $TAGTOP/log

#update filelist
find $PRJTOP -wholename $PRJTOP/.repo -prune -o -type f 2>/dev/null > $TAGTOP/filelist
find $PRJTOP -name "*" -type d > $TAGTOP/dirlist
echo "!_TAG_FILE_SORTED        2       /2=foldcase/" > $TAGTOP/filenametags
for src in $SRCLIST
do
        cd $PRJTOP/$src
        find $PRJTOP/$src -type f -printf "%f\t%p\t1\n"  2>/dev/null | sort -f >> $TAGTOP/filenametags
done

cd $PWD
